Add suspend unregister callback
sociomantic-tsunami/swarm pull request #365
Opened 2018-10-09 09:51 UTC by matthias-wende-sociomantic

This will be used in dhtproto to give applications an option to
remove instances of type ISuspendable when a suspendable request
finishes.

2018-10-09 12:19 UTC, gavin-norman-sociomantic commented
High-level question: is this an important bug fix? Our general principle with all legacy swarm code is to not change anything unless it's very important.

2018-10-09 12:31 UTC, matthias-wende-sociomantic commented
That is part of the "proper" fix to the problem described in https://github.com/sociomantic-tsunami/ocean/pull/640 (i.e. applications should remove a suspendable from the list of suspendables when a request finishes rather then keeping it in a list in a undefined state). I would consider this as a bug fix feature :).

2018-10-09 12:52 UTC, matthias-wende-sociomantic commented
Alright, as discussed IRL we not gonna merge this since the switch to neo is near ;).

2018-11-01 15:23 UTC, gavin-norman-sociomantic requested changes

2018-11-01 15:23 UTC, gavin-norman-sociomantic commented on src/swarm/client/RequestSetup.d
>          Imports needed by template.
I wouldn't mention dhtproto in the commit message specifically. This change could, in principle, be used in any proto repo.

2018-11-01 15:24 UTC, gavin-norman-sociomantic commented
Oh this should have a release note too (new feature).

2018-11-01 17:00 UTC, nemanja-boric-sociomantic approved these changes

2018-11-08 16:11 UTC, gavin-norman-sociomantic approved these changes

2018-11-08 16:11 UTC, merged